import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuctionStore } from '../../store/auctionStore';
import { formatPrice } from '../../lib/format';
import BidButton from '../../components/auction/BidButton';
import Leaderboard from '../../components/auction/Leaderboard';
import EmotionToast from '../../components/auction/EmotionToast';
import { Card, CardContent } from '../../design-system/components/ui/card';
import { Badge } from '../../design-system/components/ui/badge';
import { Separator } from '../../design-system/components/ui/separator';
import { ScrollArea } from '../../design-system/components/ui/scroll-area';
export default function AuctionPanel() {
    const { currentAuction, onlineCount, participantCount } = useAuctionStore();
    if (!currentAuction) {
        return (_jsxs("div", { className: "p-6 h-full flex flex-col items-center justify-center", children: [_jsx("div", { className: "text-4xl mb-3", children: "\uD83D\uDCE6" }), _jsx("p", { className: "text-text-secondary text-lg", children: "\u7B49\u5F85\u4E3B\u64AD\u53D1\u8D77\u7ADE\u62CD" }), _jsxs("p", { className: "text-text-tertiary text-sm mt-2", children: ["\uD83D\uDD25 ", onlineCount, " \u4EBA\u5728\u7EBF"] })] }));
    }
    return (_jsxs(ScrollArea, { className: "h-full", children: [_jsxs("div", { className: "p-4 space-y-4", children: [_jsx("div", { className: "text-center text-sm", children: _jsxs(Badge, { variant: "outline", className: "border-brand/30 text-brand", children: ["\uD83D\uDD25 ", participantCount, " \u4EBA\u6B63\u5728\u7ADE\u62CD"] }) }), _jsx(Card, { className: "bg-surface-elevated border-white/10", children: _jsx(CardContent, { className: "p-4", children: _jsxs("div", { className: "flex gap-3", children: [currentAuction.product.imageUrl ? (_jsx("img", { src: currentAuction.product.imageUrl, alt: "", className: "w-16 h-16 rounded-lg object-cover bg-surface-secondary" })) : (_jsx("div", { className: "w-16 h-16 rounded-lg bg-surface-secondary flex items-center justify-center text-2xl", children: "\uD83D\uDCE6" })), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h3", { className: "text-white font-semibold truncate", children: currentAuction.product.name }), _jsxs("div", { className: "flex items-center gap-2 mt-1.5 flex-wrap", children: [_jsxs(Badge, { variant: "secondary", className: "text-[10px] bg-surface-secondary text-text-tertiary border-0", children: ["\u52A0\u4EF7 \u00A5", formatPrice(currentAuction.rule.bidIncrement)] }), currentAuction.rule.ceilingPrice && (_jsxs(Badge, { variant: "secondary", className: "text-[10px] bg-surface-secondary text-text-tertiary border-0", children: ["\u5C01\u9876 \u00A5", formatPrice(currentAuction.rule.ceilingPrice)] }))] })] })] }) }) }), _jsxs("div", { className: "text-center py-2", children: [_jsx("div", { className: "text-text-tertiary text-xs mb-1", children: "\u5F53\u524D\u51FA\u4EF7" }), _jsx("div", { className: "text-brand text-4xl font-bold tracking-tight", children: formatPrice(currentAuction.currentPrice) })] }), _jsx(Separator, { className: "bg-white/5" }), _jsxs("div", { className: "flex justify-around text-center text-xs", children: [_jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-0.5", children: "\uD83D\uDD25 \u5728\u7EBF" }), _jsx("div", { className: "text-white font-semibold text-base", children: onlineCount })] }), _jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-0.5", children: "\uD83D\uDCB0 \u53C2\u4E0E" }), _jsx("div", { className: "text-white font-semibold text-base", children: participantCount })] }), _jsxs("div", { children: [_jsx("div", { className: "text-text-secondary mb-0.5", children: "\u23F1 \u5269\u4F59" }), _jsx("div", { className: "text-accent font-semibold text-base", children: "--" })] })] }), _jsx(Separator, { className: "bg-white/5" }), _jsx("div", { className: "max-md:hidden", children: _jsx(BidButton, { sessionId: currentAuction.sessionId }) }), _jsx(Leaderboard, {})] }), _jsx(EmotionToast, {})] }));
}
